name: Build & Test

on:
  push:
    tags: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  release_macos:
    runs-on: macos-latest

    needs: build_and_test

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release

  release_linux:
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
